Fix typo in README for submodule instructions
Corrected the spelling of "submodule" in the README file to ensure
clarity in the instructions for cloning the necessary submodules.

diff --git a/script/pre_build b/script/pre_build
--- a/script/pre_build
+++ b/script/pre_build
@@ -33,4 +33,7 @@ if [ "${BUILD_BANK}" = "bank0" ]; then
    arm-none-eabi-gcc -D BUILD_BANK=0 -E -P -x c ${OT_SRCDIR}/src/bee4/${BUILD_TARGET}/app.ld -o ${OT_SRCDIR}/src/bee4/${BUILD_TARGET}/app.ld.gen
 elif [ "${BUILD_BANK}" = "bank1" ]; then
    arm-none-eabi-gcc -D BUILD_BANK=1 -E -P -x c ${OT_SRCDIR}/src/bee4/${BUILD_TARGET}/app.ld -o ${OT_SRCDIR}/src/bee4/${BUILD_TARGET}/app.ld.gen
+else
+   echo "Error: Invalid BUILD_BANK value '${BUILD_BANK}'. Expected 'bank0' or 'bank1'."
+   exit 1
 fi
